# codemagic.yaml
# Reference: https://docs.codemagic.io/yaml-basic-configuration/

workflows:
  flutter-ci-cd:
    name: Flutter CI/CD
    # Set the Flutter version to use. 'stable', 'beta', or a specific version like '3.19.5'
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    # Trigger the build on pushes or pull requests to the 'master' branch
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run static analysis
        script: |
          flutter analyze . --no-fatal-infos --no-fatal-warnings

      - name: Run widget tests
        script: |
          flutter test
        test_report: build/test.xml # Optional: To see test results in Codemagic UI

      - name: Generate app icons
        # This script is included because 'flutter_launcher_icons' is in your pubspec.yaml
        script: |
          flutter pub run flutter_launcher_icons

      - name: Build Android Release (App Bundle)
        script: |
          flutter build appbundle --release
      
      - name: Build iOS Release (IPA)
        script: |
          # Set up keychain and add certificates
          keychain initialize
          keychain add-certificates --certificate "$IOS_CERTIFICATE" --certificate-password "$IOS_CERTIFICATE_PASSWORD"
          
          # Add and use the provisioning profile
          keychain add-provisioning-profile --profile "$IOS_PROVISIONING_PROFILE"
          xcode-project use-profiles
          
          # Install pods and build the app
          set -x # print commands for debugging
          find . -name "Podfile" -execdir pod install \;
          flutter build ipa --release --export-options-plist=$FCI_BUILD_DIR/ios/ExportOptions.plist
          
          # Clean up the keychain after the build
          keychain cleanup

    artifacts:
      # Collect the build artifacts to be downloaded from the Codemagic UI
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa
      - $FCI_BUILD_DIR/build/test.xml # Collect test report

# The 'publishing' section has been completely removed to fix the validation error.
# You can add it back later when you are ready to configure deployment.
